[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild" # Usa esbuild para empaquetar funciones, a menudo más robusto

[build]
  # Este comando instalará las dependencias de tu función antes de desplegar
  command = "npm install --prefix netlify/functions"
  publish = "." # Directorio raíz para publicar archivos estáticos
